services:
  quakewatch:
    build:
      context: .
      dockerfile: Dockerfile
    image: mlsokolova/quakewatch
    container_name: quakewatch
    ports:
      - "5000:5000"
    environment:
      MPLCONFIGDIR: /tmp/matplotlib
      QUAKEWATCH__LOG_PATH: /tmp/logs
