apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quakewatch
  name: quakewatch
  namespace: final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quakewatch
  strategy: {}
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
      - image: mlsokolova/quakewatch:2.0.0
        name: quakewatch
        resources:
          requests:
            cpu: "0.1"
            memory: "250Mi"
          limits:
            cpu: "1"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: QUAKEWATCH__LOG_PATH
          valueFrom:
            configMapKeyRef:
              name: quakewatch
              key: QUAKEWATCH__LOG_PATH
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: quakewatch
  name: quakewatch
  namespace: final-project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: quakewatch
  type: NodePort
status:
  loadBalancer: {}
