apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-tst-readiness
spec:
  containers:
  - image: nginx:1.31.0
    name: nginx
    command:  ["/bin/sh", "-c"]
    args:
    - "sleep 60 && exec /docker-entrypoint.sh nginx -g 'daemon off;'"
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
  dnsPolicy: ClusterFirst
  restartPolicy: Always
