apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-tst-configmap
  name: nginx-tst-configmap
spec:
  volumes:
    - name: class4-pvc
      persistentVolumeClaim:
        claimName: class4-pvc
    - name: nginx-conf
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: nginx-configmap
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "nginx.conf"
          path: "nginx.conf"
  containers:
  - image: nginx:1.31.0
    name: nginx
    volumeMounts:
    - mountPath: "/data"
      name: class4-pvc
    - mountPath: "/etc/nginx/nginx.conf"
      subPath: nginx.conf
      name: nginx-conf
      readOnly: true
    env:
    - name: APPLICATION
      valueFrom:
        configMapKeyRef:
          name: nginx-configmap
          key: APPLICATION
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
