---
- hosts: servers

  tasks:
  - name: get linux distribution
    command: cat /etc/issue
    register: linux_distribution

  - name: print linux distribution
    debug:
      msg: "{{ linux_distribution.stdout }}"

