resource "random_password" "terraform-gen-passwd" {
  length  = 24
  special = true
}

resource "aws_secretsmanager_secret" "random-passwd" {
  name        = "random-passwd"
  description = "Password generated by Terraform"
  recovery_window_in_days = 0 
}

resource "aws_secretsmanager_secret_version" "secret-value" {
  secret_id = aws_secretsmanager_secret.random-passwd.id

  # secret_string + random_password hits an AWS provider bug (.version_id known→unknown).
  # secret_string_wo avoids that; the password stays readable via the random_password output.
  secret_string_wo = jsonencode({
    password = random_password.terraform-gen-passwd.result
  })
  secret_string_wo_version = 1
}

output "random-passwd" {
  description = "Terraform's generated password"
  value       = random_password.terraform-gen-passwd.result
  sensitive   = true
}
