apiVersion: v1
kind: Pod
metadata:
  labels:
    run: superset
  name: superset
spec:
  containers:
  - image: amancevice/superset:6.0.0
    name: superset
    resources: 
      requests:
        cpu: "0.25"
        memory: "250Mi"
      limits:
        cpu: "0.5"
        memory: "4Gi" 
    env:
      - name: APPLICATION
        value: superset
      - name:  SUPERSET_SECRET_KEY
        value: qwe123
    command: ["/bin/sh"]
    args: 
      - "-c"
      - "superset-init --username=admin --firstname=admin --lastname=admin --email=admin@localhost  --password
=admin && gunicorn 'superset.app:create_app()'"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
#TODO: move SUPERSET_SECRET_KEY and admin user creds into kuber secrets

---
apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  selector:
    run: superset
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: NodePort


---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: airflow
  name: airflow
spec:
  containers:
  - image: puckel/docker-airflow:1.10.9
    name: airflow
    resources: 
      requests:
        cpu: "0.25"
        memory: "250Mi"
      limits:
        cpu: "0.5"
        memory: "4Gi" 
    env:
      - name: APPLICATION
        value: airflow
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  selector:
    run: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: postgres
spec:
# Retain data in a local folder after pod deletion
  volumes:
  - name: data
    hostPath:
      path: /class3-mpostgresql-data
      type: DirectoryOrCreate
  containers:
  - image: postgres:17
    name: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: qwe123
# Retain data in a local folder after pod deletion
    volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
#TODO: move POSTGRES_PASSWORD to kuber secrets
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: postgres
  type: NodePort
status:
  loadBalancer: {}
