apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-health-check
  namespace: final-project
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 60
  failedJobsHistoryLimit: 180
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: check
            image: python:slim-bookworm
            command: ["python3"]
            args:
              - "-c"
              - |
                import json
                import urllib.request
                url = "http://quakewatch:5000/health"
                with urllib.request.urlopen(url, timeout=10) as response:
                    raw_data = response.read().decode('utf-8')
                    data = json.loads(raw_data)
                status = data["status"]
                if status != "ok": exit(1)
                