kind: PersistentVolume
apiVersion: v1
metadata:
  name: class4-pv
  labels:
    type: local
  namespace: class4
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/class4/"
    type: "DirectoryOrCreate"
